import React, { useState, useEffect } from 'react';
import { Container, Row, Col } from 'react-bootstrap';
import { PortfolioProvider } from '../context/context';
import {aboutData} from '../mock/data';

function App() {
  const [about, setAbout] = useState({});

  useEffect(() => {  
    setAbout({ ...aboutData });
  }, []);

  return (
    <PortfolioProvider value={{about}}>
      <Container>
        <Row>
          <Col lg='12' className='mt-5'>
            <h1 className='mt-5 pt-5 pb-5'>Disclaimer</h1>
            <p>
            Last updated: 2022-02-01
            </p>
            <div className='mt-3 mb-3'>
              <h3>WEBSITE DISCLAIMER</h3>
              <p>
                Please read this Disclaimer carefully before using Niche.lk.
                <br/>
                This document is an electronic record in terms of Electronic Transactions Act. No 19 of 2006 of Sri Lanka and rules thereunder as applicable and the amended provisions pertaining to electronic records in various statutes as amended by the Electronics Transactions Act No. 19 of 2006.
                <br/>
                This electronic record is generated by a computer system and does not require any physical or digital signatures.
              </p>
            </div>
            <div className='mb-3'>
              <h3>WEBSITE DISCLAIMER</h3>
              <p>
              Welcome to Niche.lk (hereinafter sometimes referred to as “Company”, “we", "us" or "NICHE"). We are an online marketplace and these are the disclaimers governing your access and use of NICHE along with its related sub-domains, sites, mobile app, services and tools (collectively referred to as the "Site"). By using the Site, you hereby accept that you have read, understood, and agree to these disclaimers (including the linked information herein. This Disclaimer is deemed effective upon your use of the Site which signifies your acceptance of the same. If you do not agree to be bound by this Disclaimer please do not access, register with or use this Site. 
              NICHE reserves the right to change, modify, add, or remove portions of this Disclaimer at any time without any prior notification. Changes will be effective when posted on the Site with no other notice provided. Please check this Disclaimer regularly for updates. Your continued use of the Site following the posting of changes to this Disclaimer constitutes your acceptance of those changes.
              </p>
            </div>
            <div className='mb-3'>
              <h3>GENERAL USE DISCLAIMER</h3>
              <p>
              The information provided by NICHE on the “Site” is for general informational purposes only. All information on the Site is provided in good faith, however we make no representation or warranty of any kind, express or implied, regarding the accuracy, adequacy, validity, reliability, availability, or completeness of any information on the Site.
              <br/>
              Under no circumstance shall we have any liability to you except as may be provided for in our policies for any loss or damage of any kind incurred as a result of the use of the site or reliance on any information provided on the site. Your use of the site and your reliance on any information on the site is solely at your own risk.
              <br/>
              The site, and any content available on the site, are provided on an “as-is” and “as available” basis. To the fullest extent permitted by law, we disclaim all warranties, express or implied, including but not limited to all warranties of merchantability, fitness for a particular purpose, title and non-infringement. You expressly agree that use of the site is at your sole risk and you assume full responsibility for all costs associated with all necessary servicing or repairs of any equipment you use in connection with your use of the site. Neither we nor any of our business partners represent or warrant that the site will be uninterrupted or error-free, that defects, if any, will be corrected, or that the site is free of viruses or other harmful components; nor do we or they make any representations or warranties about the accuracy, reliability, currency, quality, performance or suitability of the site or any content available on the site. In the event of any problem with the site or any content, you agree that your sole remedy is to cease using the site. All products and services listed or purchased on or through the site are subject only to any applicable express warranties. To the fullest extent permissible by applicable law, we disclaim all other warranties of any kind, either express or implied, including, but not limited to, any implied warranties of merchantability or fitness for a particular purpose, with respect to products and services listed or purchased on or through the site. We disclaim any and all liability for product defect or failure, claims that are due to normal wear, product misuse, abuse, product modification, improper product selection, non-compliance with any codes, or misapplication. Notwithstanding anything to the contrary.
              </p>
            </div>
            <div className='mb-3'>
              <h3>DISCLAIMER OF WARRANTIES AND LIMITATION OF LIABILITY</h3>
              <p>
              We do not guarantee, represent or warrant that your use of our service will be uninterrupted, timely, secure or error-free.
              <br/>
              We do not guarantee, represent or warrant that the results that may be obtained from the use of the service will be accurate or reliable.
              <br/>
              You agree that from time to time we may remove the service for indefinite periods of time or cancel the service at any time, without notice to you.
              <br/>
              You expressly agree that your use of, or inability to use, the service is at your sole risk. The service and all products and services delivered to you through the service are (except as expressly stated by us) provided ‘as is’ and ‘as available’ for your use, without any representation, warranties or conditions of any kind, either express or implied, including all implied warranties or conditions of merchantability, merchantable quality, fitness for a particular purpose, durability, title, and non-infringement.
              <br/>
              In no case shall NICHE, our directors, officers, employees, affiliates, agents, contractors, interns, suppliers, service providers or licensors be liable for any injury, loss, claim, or any direct, indirect, incidental, punitive, special, or consequential damages of any kind, including, without limitation lost profits, lost revenue, lost savings, loss of data, replacement costs, or any similar damages, whether based in contract, tort (including negligence), strict liability or otherwise, arising from your use of any of the service or any products procured using the service, or for any other claim related in any way to your use of the service or any product, including, but not limited to, any errors or omissions in any content, or any loss or damage of any kind incurred as a result of the use of the service or any content (or product) posted, transmitted, or otherwise made available via the service, even if advised of their possibility. Because some states or jurisdictions do not allow the exclusion or the limitation of liability for consequential or incidental damages, in such states or jurisdictions, our liability shall be limited to the maximum extent permitted by law.
              </p>
            </div>
            <div className='mb-3'>
              <h3>EXTERNAL LINKS DISCLAIMER</h3>
              <p>
              The Site may contain (or you may be sent through the Site) links to other websites or content belonging to or originating from third parties or links to websites and features. Such external links are not investigated, monitored, or checked for accuracy, adequacy, validity, reliability, availability, or completeness by us.
              <br/>
              We do not warrant, endorse, guarantee, or assume responsibility for the accuracy or reliability of any information offered by third-party websites linked through the site or any website or feature linked in any banner or other advertising. We will not be a party to or in any way be responsible for monitoring any transaction between you and third-party providers of products or services.              
              </p>
            </div>
            <div className='mb-3'>
              <h3>AFFILIATES DISCLAIMER</h3>
              <p>
              The Site may contain links to affiliate websites, and we may receive an affiliate commission for any purchases or actions made by you on the affiliate websites using such links.
              </p>
            </div>
            <div className='mb-3'>
              <h3>TESTIMONIALS DISCLAIMER</h3>
              <p>
              The Site may contain testimonials by users of our products and/or services. These testimonials reflect the real-life experiences and opinions of such users. However, the experiences are personal to those particular users, and may not necessarily be representative of all users of our products and/or services. We do not claim, and you should not assume that all users will have the same experiences.
              </p>
            </div>
            <div className='mb-3'>
              <h3>YOUR INDIVIDUAL RESULTS MAY VARY</h3>
              <p>
              The testimonials on the Site are submitted in various forms such as text, audio and/or video, and are reviewed by us before being posted. They appear on the Site verbatim as given by the users, except for the correction of grammar or typing errors. Some testimonials may have been shortened for the sake of brevity, where the full testimonial contained extraneous information not relevant to the general public.
              <br/>
              The views and opinions contained in the testimonials belong solely to the individual user and do not reflect our views and opinions.
              </p>
            </div>
            <div className='mb-3'>
              <h3>ERRORS AND OMISSIONS DISCLAIMER</h3>
              <p>
              While we have made every attempt to ensure that the information contained in this site has been obtained from reliable sources, NICHE is not responsible for any errors or omissions or for the results obtained from the use of this information. All information in this site is provided “as is”, with no guarantee of completeness, accuracy, timeliness or of the results obtained from the use of this information, and without warranty of any kind, express or implied, including, but not limited to warranties of performance, merchantability, and fitness for a particular purpose.
              In no event will NICHE, its related partnerships or corporations, or the partners, agents or employees thereof be liable to you or anyone else for any decision made or action taken in reliance on the information in this Site or for any consequential, special or similar damages, even if advised of the possibility of such damages.
              </p>
            </div>
            <div className='mb-3'>
              <h3>GUEST CONTRIBUTORS’ DISCLAIMER</h3>
              <p>
              This Site may include content from guest contributors and any views or opinions expressed in such posts are personal and do not represent those of NICHE or any of its staff or affiliates unless explicitly stated.
              </p>
            </div>
            <div className='mb-3'>
              <h3>LOGOS AND TRADEMARKS DISCLAIMER</h3>
              <p>
              All logos and trademarks of parties referenced on NICHE are the trademarks and logos of their respective owners. Any inclusion of such trademarks or logos does not imply or constitute any approval, endorsement, or sponsorship by NICHE of such owners.
              </p>
            </div>
            <div className='mb-5'>
              <h3>CONTACT US</h3>
              <p>
              Should you have any feedback, comments, requests for technical support or other inquiries, please contact us by email: support@niche.lk.
              </p>
            </div>

          </Col>
        </Row>      
      </Container>
    </PortfolioProvider>
  );
}

export default App;